apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api
  namespace: fcg
  labels:
    app: payments-api
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-api
  template:
    metadata:
      labels:
        app: payments-api
        tier: backend
    spec:
      containers:
        - name: payments-api
          image: fcg-payments-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: payments-api-config
          env:
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: payments-api-secrets
                  key: RabbitMQ__Password
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
