apiVersion: v1
kind: Service
metadata:
  name: payments-api-service
  namespace: fcg
  labels:
    app: payments-api
spec:
  selector:
    app: payments-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
# NodePort para testes locais
apiVersion: v1
kind: Service
metadata:
  name: payments-api-nodeport
  namespace: fcg
spec:
  selector:
    app: payments-api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30083
  type: NodePort
